[[bin]]
name = "whichdoc"
path = "src/main.rs"

[dependencies]
atty = "0.2"
edtui = { features = ["arboard", "syntax-highlighting"], version = "0.9.8" }
facet = "0.30"
facet-toml = "0.30"
ratatui = "0.29"
serde = { features = ["derive"], version = "1" }
serde_json = "1"
syntect = { default-features = false, features = [
  "default-fancy",
], version = "5.3.0" }

[package]
authors = ["Louis Maddox <louismmx@gmail.com>"]
categories = ["command-line-utilities", "development-tools"]
description = "A cargo documentation diagnostics-driven editor"
documentation = "https://docs.rs/whichdoc/"
edition = "2021"
homepage = "https://github.com/lmmx/whichdoc"
keywords = ["cargo", "diagnostics", "documentation", "tui"]
license = "MIT"
name = "whichdoc"
readme = "README.md"
repository = "https://github.com/lmmx/whichdoc"
rust-version = "1.90"
version = "0.1.4"

[package.metadata.binstall]
pkg-fmt = "tgz"
pkg-url = "https://github.com/lmmx/whichdoc/releases/download/whichdoc-v{ version }/whichdoc-{ target }-v{ version }.tar.gz"

[package.metadata.binstall.overrides.aarch64-pc-windows-msvc]
pkg-fmt = "zip"
pkg-url = "https://github.com/lmmx/whichdoc/releases/download/whichdoc-v{ version }/whichdoc-aarch64-pc-windows-msvc-v{ version }.zip"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"
pkg-url = "https://github.com/lmmx/whichdoc/releases/download/whichdoc-v{ version }/whichdoc-x86_64-pc-windows-msvc-v{ version }.zip"

[profile.dev]
codegen-units = 256
debug = false
lto = false
opt-level = 0
strip = "debuginfo"

[profile.release]
codegen-units = 1
debug = false
lto = "thin"
opt-level = 2
strip = "symbols"

[lints.clippy]
all = "deny"
cargo = "deny"
pedantic = "deny"

[lints.rust]
unsafe_code = "forbid"
# missing_docs = "deny"
